Update CI with explicit py version envs

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -11,92 +11,77 @@ on:
 jobs:
   pre-commit:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-
-    - name: Run pre-commit
-      uses: pre-commit/action@v3.0.1
+      - uses: actions/checkout@v4
+      - uses: pre-commit/action@v3.0.1
 
   test-matrix:
-    name: Test (${{ matrix.os }}, ${{ matrix.environment }})
+    name: Test (${{ matrix.os }}, ${{ matrix.toolkit }}-${{ matrix.extras }}-py${{ matrix.python-version }})
     needs: pre-commit
+    runs-on: ${{ matrix.os }}
 
     env:
       OE_LICENSE: ${{ github.workspace }}/oe_license.txt
+      PIXI_ENV: ${{ matrix.toolkit }}-${{ matrix.extras }}-py${{ matrix.python-version }}
 
-    needs: pre-commit
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest]
-        pixi-environment: [default, pydantic-1-cpu, ambertools, openeye]
-      fail-fast: false
-
-    runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
         os: [ubuntu-latest, macos-latest]
-        pixi-environment:
-          # Standard CPU envs with ambertools and openeye
-          - openeye-fe-examples-cpu-py311
-          - openeye-fe-examples-cpu-py312
-          - ambertools-fe-examples-cpu-py311
-          - ambertools-fe-examples-cpu-py312
-
-          # Stripped down envs with no ambertools
-          - openeye-cpu-py311
-          - openeye-cpu-py312
-
-          # CUDA 12 envs
-          - ambertools-fe-examples-cu12-py311
-          - ambertools-fe-examples-cu12-py312
-
-          # Pydantic 1 envs
-          - ambertools-examples-pydantic-1-cpu-py311
-          - ambertools-examples-pydantic-1-cpu-py312
-          - ambertools-examples-pydantic-1-cu12-py311
-          - ambertools-examples-pydantic-1-cu12-py312
+        python-version: ["311", "312"]
+        toolkit: [openeye, ambertools]
+        extras: [fe-examples-cpu, fe-examples-cu12, cpu, examples-pydantic-1-cpu, examples-pydantic-1-cu12]
+        exclude:
+          # No CUDA or pydantic 1 envs with OE
+          - toolkit: openeye
+            extras: fe-examples-cu12
+          - toolkit: openeye
+            extras: examples-pydantic-1-cpu
+          - toolkit: openeye
+            extras: examples-pydantic-1-cu12
+          # CUDA envs don't run on macOS
+          - os: macos-latest
+            extras: fe-examples-cu12
+          - os: macos-latest
+            extras: examples-pydantic-1-cu12
 
     steps:
-    - uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-    - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
-      env:
-        OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
-      run: echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}
+      - name: Write OE license file
+        env:
+          OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
+        run: echo "${OE_LICENSE_TEXT}" > "${OE_LICENSE}"
 
-    - name: Setup pixi
-      uses: prefix-dev/setup-pixi@v0.9.3
-      with:
-        pixi-version: v0.62.2
-        cache: true
-        environments: ${{ matrix.pixi-environment }}
+      - name: Setup pixi
+        uses: prefix-dev/setup-pixi@v0.9.3
+        with:
+          pixi-version: v0.63.2
+          cache: true
+          environments: ${{ env.PIXI_ENV }}
 
-    - name: Run tests
-      run: pixi run -e ${{ matrix.pixi-environment }} test
+      - name: Run tests
+        run: pixi run -e "${{ env.PIXI_ENV }}" test
 
-    - name: Test examples
-      if: ${{ contains(matrix.pixi-environment, 'examples') }}
-      run: pixi run -e ${{ matrix.pixi-environment }} test-examples
+      - name: Test examples
+        if: contains(env.PIXI_ENV, 'examples')
+        run: pixi run -e "${{ env.PIXI_ENV }}" test-examples
 
-    - name: CodeCov
-      uses: codecov/codecov-action@v4.1.1
-      with:
-        file: ./coverage.xml
-        flags: unittests
-        token: ${{ secrets.CODECOV_TOKEN }}
+      - name: CodeCov
+        uses: codecov/codecov-action@v5
+        with:
+          file: ./coverage.xml
+          flags: unittests
+          token: ${{ secrets.CODECOV_TOKEN }}
 
   test:
     needs: test-matrix
     runs-on: ubuntu-latest
     if: always()
-
     steps:
-    - name: Check test matrix result
-      run: |
-        if [[ "${{ needs.test-matrix.result }}" != "success" ]]; then
-          echo "One or more test matrix jobs failed or were cancelled."
-          exit 1
-        fi
+      - name: Check test matrix result
+        run: |
+          if [[ "${{ needs.test-matrix.result }}" != "success" ]]; then
+            echo "One or more test matrix jobs failed or were cancelled."
+            exit 1
+          fi
