Switch to pixi (#131)
* Fix tests failing due to changes in dependencies

* Handle changes in scipy.logsumexp behaviour
* Add CMMMotion remover when creating system from xml to match change in
  behaviour in Interchange

* Ignore CMMotionRemover when comparing number of forces

* Switch to pixi

* Update setup-pixi GHA runner

* Switch to pixi with docker

* Add explicit CUDA 12 env

* Exclude md notebook from examples test

* Specify pytorch-gpu for use with CUDA envs

* Only installed required envs in CI

* Fix selection of pixi envs in CI

* Add mac platforms

* Add osx-arm64 to CI

* Add seperate pre-commit workflow

* Remove Makefile (replaced by pixi commands in pyproject.toml)

* Use seperate solve groups to allow cpu pytorch version in default

* Add pre-commit to start of CI

* Update pre-commit

* Exclude offxml from end-of-file-fixer

* Add overall test reporter stage in CI for branch protection rule

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,7 +1,7 @@
 name: CI
 
 concurrency:
-  group: ${{ github.ref }}
+  group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 on:
@@ -9,41 +9,55 @@ on:
   pull_request: { branches: [ "main" ] }
 
 jobs:
-  test:
-
+  pre-commit:
     runs-on: ubuntu-latest
-    container: condaforge/mambaforge:latest
 
     steps:
-    - uses: actions/checkout@v3.3.0
+    - name: Checkout
+      uses: actions/checkout@v4
 
-    - name: Setup Conda Environment
+    - name: Run pre-commit
+      uses: pre-commit/action@v3.0.1
+
+  test-matrix:
+    needs: pre-commit
+    strategy:
+      matrix:
+        include:
+          - os: ubuntu-latest
+            pixi-platform: linux-64
+          - os: macos-latest
+            pixi-platform: osx-arm64
+      fail-fast: false
+
+    runs-on: ${{ matrix.os }}
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    - name: Setup pixi
+      uses: prefix-dev/setup-pixi@v0.9.3
+      with:
+        pixi-version: v0.62.2
+        cache: true
+        environments: default pydantic-1-cpu
+
+    - name: Run tests with pydantic >=2
       run: |
-        apt update && apt install -y git make
+        pixi run test
 
-        make env
-
-    - name: Lint
-      run: make lint
-    
-    - name: Test
-      run: make test
-
-    - name: Test Examples
-      run: make test-examples
-    
-    - name: Build Docs
-      run: make docs
-
-    - name: Reconstruct environment with Pydantic 1.0
+    - name: Run tests with pydantic <2
       run: |
-        # TODO: Remove this once pydantic 1.0 support is dropped
-        #       We remove absolv as femto needs pydantic >=2
-        mamba remove  --name smee --yes "absolv" "absolv-base" "femto" "pint" --force
-        mamba install --name smee --yes "pydantic <2"
+        pixi run --environment pydantic-1-cpu test
 
-    - name: Test with Pydantic 1.0
-      run: make test
+    - name: Test examples with pydantic >=2
+      run: |
+        pixi run test-examples
+
+    - name: Build docs
+      run: |
+        pixi run docs
 
     - name: CodeCov
       uses: codecov/codecov-action@v4.1.1
@@ -51,3 +65,16 @@ jobs:
         file: ./coverage.xml
         flags: unittests
         token: ${{ secrets.CODECOV_TOKEN }}
+
+  test:
+    needs: test-matrix
+    runs-on: ubuntu-latest
+    if: always()
+
+    steps:
+    - name: Check test matrix result
+      run: |
+        if [[ "${{ needs.test-matrix.result }}" != "success" ]]; then
+          echo "One or more test matrix jobs failed or were cancelled."
+          exit 1
+        fi
